name: Notify Slack on PR

on:
  pull_request:
    types: [opened, edited, reopened]  # Puedes ajustar los tipos de eventos seg칰n tus necesidades

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "#backend",
              "text": "游닉 Atenci칩n: Se ha creado una nueva Pull Request\n*T칤tulo:* ${{ github.event.pull_request.title }}\n*Autor:* ${{ github.event.pull_request.user.login }}\n*Descripci칩n:* ${{ github.event.pull_request.body }}\n*Enlace:* ${{ github.event.pull_request.html_url }}\n*Rama base:* ${{ github.event.pull_request.base.ref }}\n*Rama de comparaci칩n:* ${{ github.event.pull_request.head.ref }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
