name: Notify Slack on PR Creation

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "#backend",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "📢 New Pull Request Created"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Title:* ${{ github.event.pull_request.title }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:* ${{ github.event.pull_request.user.login }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Description:* ${{ github.event.pull_request.body }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Link:* <${{ github.event.pull_request.html_url }}|View PR>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Base Branch:* ${{ github.event.pull_request.base.ref }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Comparison Branch:* ${{ github.event.pull_request.head.ref }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
