name: Notify Slack on PR State Change

on:
  pull_request:
    types: [closed, opened, reopened, edited]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification on PR state change
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Your pull request (#${{ github.event.pull_request.number }}) has been '"eeee"'.",
            "channel": "@${{ github.event.pull_request.user.login }}"
          }' $SLACK_WEBHOOK_URL
