name: Notify Slack on PR State Change

on:
  pull_request:
    types: [closed, opened, reopened, edited]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification on PR state change
        uses: slackapi/slack-github-action@v3
        with:
          slack_token: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: "@${{ github.event.pull_request.user.login }}"
          text: |
            Your pull request (#${{ github.event.pull_request.number }}) has been:
            * **${{ github.event.action }}**
