name: Notificación a Slack al cerrar un Pull Request

on:
  pull_request:
    types: [closed]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a Slack
        run: |
          STATUS=""

          if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            STATUS="merged"
          else
            STATUS="declined"
          fi

          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Tu pull request (#${{ github.event.pull_request.number }}) ha sido \""${STATUS}"\".",
            "channel": "#general"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
