name: Notificar a Slack sobre cambios en el estado de un PR

on:
  pull_request:
    types: [closed, opened, reopened, edited]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a Slack sobre cambios en el estado de un PR
        run: |
         STATUS=""

          if [ "${{ github.event.pull_request.state }}" = "closed" ]; then
            if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
              STATUS="merged"
            else
              STATUS="declined"
            fi
          elif [ "${{ github.event.pull_request.state }}" = "open" ]; then
            if [ "${{ github.event.action }}" = "opened" ]; then
              STATUS="opened"
            elif [ "${{ github.event.action }}" = "reopened" ]; then
              STATUS="reopened"
            elif [ "${{ github.event.action }}" = "edited" ]; then
              STATUS="edited"
            fi
          fi
          
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Tu pull request (#${{ github.event.pull_request.number }}) ha sido '"${STATUS}"'.",
            "channel": "@Fer1196"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

